version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
      - dependency-name: "moose"
    schedule:
      interval: "weekly"
      time: "01:45"
    open-pull-requests-limit: 1 
    labels:
      - "Comp:Core"
      - "Priority:1-Critical" 
    reviewers:
      - "smpark7"
      - "nglaser3"