version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
      - dependency-name: "moose"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "auto_update_moose"
    open-pull-requests-limit: 1 
    labels:
      - "Comp:Core"
      - "Priority:1-Critical" 
